name: Foundry upgrade tests
description: Runs full forge test suite given a protocol and a network

inputs:
  protocol:
    description: The protocol against which to run the forge test suite.
    required: true
  network:
    description: The network against which to run the forge test suite.
    required: true
  alchemyKey:
    description: The Alchemy key giving access to a private RPC.
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: yarn

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Foundry fork cache
      uses: actions/cache@v3
      with:
        path: ~/.foundry/cache
        key: foundry-${{ hashFiles('Makefile', 'foundry.toml') }} # where fork block numbers & RPC are stored

    - name: Foundry compilation cache
      uses: actions/cache@v3
      with:
        path: |
          cache
          out
        key: ${{ github.base_ref || github.ref_name }}-foundry-${{ inputs.protocol }}-${{ inputs.network }} # always keep compiled contracts from base branch

    - name: Run upgrade tests
      run: make ci-upgrade
      shell: bash
      env:
        PROTOCOL: ${{ inputs.protocol }}
        NETWORK: ${{ inputs.network }}
        ALCHEMY_KEY: ${{ inputs.alchemyKey }}
