methods {
    getAssetsIn(address)                                                        returns (address[])                 => DISPATCHER(true)
    checkMembership(address, address)                                           returns (bool)                      => DISPATCHER(true)
    enterMarkets(address[])                                                     returns (uint256[])                 => DISPATCHER(true)
    exitMarket(address)                                                         returns (uint256)                   => DISPATCHER(true)
    mintAllowed(address, address, uint256)                                      returns (uint256)                   => DISPATCHER(true)
    mintVerify(address, address, uint256, uint256)                                                                   => DISPATCHER(true)
    redeemAllowed(address, address, uint256)                                    returns (uint256)                   => DISPATCHER(true)
    redeemVerify(address, address, uint256, uint256)                                                                => DISPATCHER(true)
    borrowAllowed(address, address, uint256)                                    returns (uint256)                   => DISPATCHER(true)
    borrowVerify(address, address, uint256)                                                                         => DISPATCHER(true)
    repayBorrowAllowed(address, address, address, uint256)                      returns (uint256)                   => DISPATCHER(true)
    repayBorrowVerify(address, address, address, uint256, uint256)                                                  => DISPATCHER(true)
    liquidateBorrowAllowed(address, address, address, address, uint256)         returns (uint256)                   => DISPATCHER(true)
    liquidateBorrowVerify(address, address, address, address, uint256, uint256)                                     => DISPATCHER(true)
    seizeAllowed(address, address, address, address, uint256)                   returns (uint256)                   => DISPATCHER(true)
    seizeVerify(address, address, address, address, uint256)                                                        => DISPATCHER(true)
    transferAllowed(address, address, address, uint256)                         returns (uint256)                   => DISPATCHER(true)
    transferVerify(address, address, address, uint256)                                                              => DISPATCHER(true)
    liquidateCalculateSeizeTokens(address, address, uint256)                    returns (uint256, uint256)          => DISPATCHER(true)
    getAccountLiquidity(address)                                                returns (uint256, uint256, uint256) => DISPATCHER(true)
    getHypotheticalAccountLiquidity(address, address, uint256, uint256)         returns (uint256, uint256, uint256) => DISPATCHER(true)
}