#!/bin/sh

. "$(dirname "$0")/_/husky.sh"

COMMIT_MSG=$(head -n 1 "$1")

BRANCH_NAME=$(git branch | grep "*" | sed "s/* //")
APPEND_COMMIT_MSG=" (${BRANCH_NAME##*/})"

if ! test "$COMMIT_MSG" != "${COMMIT_MSG#*"$APPEND_COMMIT_MSG"}"; then
    echo "$COMMIT_MSG$APPEND_COMMIT_MSG\n$(tail -n +2 "$1")" > "$1"
fi
