#!/bin/sh

. "$(dirname "$0")/_/husky.sh"

COMMIT_MSG=$(cat "$1")

BRANCH_NAME=$(git branch --show-current)
PREPEND_COMMIT_MSG="[${BRANCH_NAME##*/}] "

case $COMMIT_MSG in
    "$PREPEND_COMMIT_MSG"*) ;;
    *)                      echo "$PREPEND_COMMIT_MSG$COMMIT_MSG" > "$1"
esac
