#!/bin/sh

. "$(dirname "$0")/_/husky.sh"


CHANGED_FILES=$(git diff --staged --name-only --diff-filter=d | grep -e "\.ts$" -e "\.sol$" | xargs)

if [ -n "$CHANGED_FILES" ]; then
    yarn prettier --write $CHANGED_FILES
    git add $CHANGED_FILES
fi
