name: Storage layout snapshot check

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    paths:
      - lib/**
      - src/common/**
      - src/compound/**
      - "*.lock"
      - remappings.txt
      - .github/workflows/ci-storage-check-compound.yml

jobs:
  check:
    name: morpho-compound
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run tests
        run: make storage-layout-check
        env:
          PROTOCOL: compound
